### PR TITLE
Blog Post Markdown Conversion

### PR DESCRIPTION
**Pull request by Pyrrh**
- replaced old files and folders due to package conflicts and/or corruption
- completed Java conversion script for HTML to markdown
- All converted blog posts added to repo

### CODE REVIEW

**Comment by sreynen** [comment]
This is definitely progress, so I'm fine merging if you want, but noting some issues:

1) In content, paragraph `<p>` tags have been replaced by `<br>` tags. I prefer the `<p>` tags, as they are more meaningful and give more styling control.
2) In the frontmatter, the "path" values are mostly wrong. E.g. on this post: http://typewriting.org/2002/12/24/Giving_Seasoning/ the path should be `/2002/12/24/Giving_Seasoning` but it's `/2002/12/24/GivingSeasoning`, with the `_` removed.
3) Related, the file names currently match the path values, and it would be nice to change the file names as well, to make it easier to find a file from a given path.
4) `gatsby build` throws an error: `error GraphQL Error Unknown argument `formatString`, which seems to because it doesn't understand the date format. I was able to get past that error (and to a new error) by changing the date format to just the data with dashes, e.g. `date: "2014-03-12"` and putting time in a separate field, e.g. `time: "04:21:48"`.

**Comment by Pyrrh** [comment]
Added a couple more commits to resolve items 1-3. I'm not sure how to troubleshoot item 4 because I have a classic case of "works on my machine". I made sure to add the package-lock in on the most recent commit -- could you verify that you've got all the matching packages installed? 

---
Build Proof: 
success open and validate gatsby-config — 0.130 s
success load plugins — 0.247 s
success onPreInit — 0.410 s
success delete html and css files from previous builds — 1.184 s
success initialize cache — 0.013 s
success copy gatsby files — 0.032 s
success onPreBootstrap — 0.017 s
success source and transform nodes — 1.310 s
success building schema — 0.459 s
success createPages — 1.723 s
success createPagesStatefully — 0.357 s
success onPreExtractQueries — 0.000 s
success update schema — 0.329 s
success extract queries from components — 0.264 s
success run graphql queries — 0.053 s — 7/7 132.39 queries/second
success write out page data — 0.049 s
success write out redirect data — 0.005 s
⠈ onPostBootstrapdone generating icons for manifest
success onPostBootstrap — 0.442 s

info bootstrap finished - 10.366 s

success Building production JavaScript and CSS bundles — 9.123 s
success Building static HTML for pages — 2.164 s — 887/887 519.72 pages/second
Generated public/sw.js, which will precache 15 files, totaling 231810 bytes.
info Done building in 22.093 sec

---

**Comment by sreynen** [comment]
#1 looks better, but I still see `<br>`  between `</p><p>` paragraph boundaries. #2 and #3 look good to me. I wiped my node_modules and ran `npm install` again, but I still get the error on #4. Maybe we're using different versions of Gatsby CLI? `gatsby --version` says 2.4.6 for me. I get success through `update schema`, but then it throws the error. I'm also running `gatsby build` from within `/gatsby_files/typewriting_posts`

I'm also fine merging this if you want to move on and figure out the rest later.

**Comment by Pyrrh** [comment]
On item 1 -- it looks to me like the remaining <br> are taking the place of the /r/n which don't render properly in markdown. Could you confirm whether you'd like the /r/n removed entirely, replaced by something else, or left as-is? 

On item 4 -- when I run gatsby --version my environment is stating 1.1.58. However, because the project is dependent on version 2.0.19 or higher of gatsby, I believe that `gatsby --version` is actually returning the version of the CLI that is installed. 

There was a point when I had a more up to date version of graphql installed and referenced in the dependencies, but it had a bug that prevented code from working so I reverted to one version previous. 0.13.2 will run but 0.14.0 is broken. It was hard to track down that github issue but reverting solved it. I don't believe 0.14.0 has been fixed at this time. Perhaps that is causing the issue instead

**Comment by sreynen** [comment]
I think the \r\n can be left as-is. They aren't intended to be rendered, just to visually break up the paragraphs when writing. I'll continue to try to get gatsby to run locally, but it's more important that it runs on the server building it, so maybe we should focus on that next. For now, merging this.

**Pull request merged**
